### ISSUE TITLE
Convert all date/time to epoch time

### ISSUE THREAD

**Issue by brandomr** [jataware/mixmasta#9]
Uncharted will assume that any time field (even if not the *primary time*) should be converted to epoch time. So we should update the [`normalizer` function](https://github.com/jataware/mixmasta/blob/master/mixmasta/mixmasta.py#L271) to find any time field, not just the primary ones and convert any time field to epoch time.

**Comment by brandomr** [comment]
@BecketTrotter when you have a chance, can you generate a dummy test data set that has multiple time fields plus a dummy mapper file for us to use to fix this issue?

**Comment by GoogleSheets** [comment]
It looks like this is as simple as changing mixmasta.py ln 271 from 

`time_cols = [kk for kk, vv in mapper.items() if vv["Primary_time"] == "true"]`

to 

`time_cols = [kk for kk, vv in mapper.items() if vv["Type"] == "DATE/TIME"]`

Let me know if I am missing something. Otherwise, am able to run in docker, modify the code and then reinstall with ```python3 setup.py install ```; not sure if there is a more efficient way to do this.

Also, I tried opening the output .gzip files with 7-Zip; no go:
![image](https://user-images.githubusercontent.com/39390266/119675829-5ed70680-be0b-11eb-8cac-fe6fc9f12945.png)

**Comment by brandomr** [comment]
@GoogleSheets I think that is right. The issue is that we have a dependency here on Spacetag and how it might tag date or time. Currently this is `DATE/TIME` (see this [line of Spacetag code](https://github.com/jataware/spacetag/blob/main/annotate/views.py#L19)).

To open the gzipped parquet you will need to:

```
pip install pyarrow
pip install pandas
```

then:

```
import pandas as pd
df = pd.read_parquet('path_to_file.parquet.gzip')
```

The way this should be tested is by generating multiple `DATE/TIME` field in a dataset, but only labelling one as primary. The primary should end up in the `timestamp` column; the others should end up as epoch time stamped features.

## Testing

You should be able to run `python3 setup.py develop` instead of `install` and the package will be linked to your repo so changes you make there will "auto-build" in the installed package. See [this SO post](https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install). 

Or, you can build the Mixmasta docker container and run some tests that way (e.g. `docker build -t mixmasta .`) then follow instructions in `docs/docker.md` on how to run it.
